version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: '10 minuted'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: '10 minutes'
